### ISSUE TITLE
Failure to enable

### ISSUE THREAD

**Issue by richard-hajek** [lihop/godot-xterm#1]
When attempted enable is performed, file godot_xterm/buffer/buffer_line.gd throws error at line 135

![image](https://user-images.githubusercontent.com/29554823/92412411-162bd000-f14c-11ea-8455-48754aef11ad.png)

**Comment by lihop** [comment]
I think it's related to this issue https://github.com/godotengine/godot/issues/39861. This code was written using Godot 3.2.1, but shadowing a variable now throws an error with 3.2.2.

**Comment by lihop** [comment]
Closed by #2
