### ISSUE TITLE
Try libtmt as an alternative to libtsm

### ISSUE THREAD

**Issue by lihop** [lihop/godot-xterm#38]
[libtmt](https://github.com/deadpixi/libtmt) has a similar purpose to libtsm, but it is smaller and simpler.
Some current issues such as wide character support (#17) might be resolved by switching to libtmt.
But there are some limitations such as lack of mouse support (#4).
In any case, I think it is worth plugging in and trying.

**Comment by lihop** [comment]
The libtmt library is ok, but the libtsm is performing much better now after d2f073d7aed9a9f5de790b1463c563b05f0707ac and the upgrades to libtsm. And libtmt lacks too many features in comparison with libtsm (such as true color support). So I will stick with libtsm.

The libtmt code is quite small though (just over 500 lines of C, including comments and whitespace). So one idea might be to port libtmt to gdscript as a non GDNative fallback.

**Comment by supremestdoggo** [comment]
> The libtmt library is ok, but the libtsm is performing much better now after [d2f073d](https://github.com/lihop/godot-xterm/commit/d2f073d7aed9a9f5de790b1463c563b05f0707ac) and the upgrades to libtsm. And libtmt lacks too many features in comparison with libtsm (such as true color support). So I will stick with libtsm.
> 
> The libtmt code is quite small though (just over 500 lines of C, including comments and whitespace). So one idea might be to port libtmt to gdscript as a non GDNative fallback.

If this port hasn't been made already, I'd love to help (or even port it myself).

**Comment by lihop** [comment]
> If this port hasn't been made already, I'd love to help (or even port it myself).

@supremestdoggo Yes, feel free to have a go at porting it.

I attempted a port previously, but don't have the files anymore sorry. The main problem I encountered was libmt's heavy use of macros which I found difficult to translate into GDScript. I hope you might have more success!

**Comment by supremestdoggo** [comment]
The (currently incomplete) port's [here](https://github.com/supremestdoggo/gdscript-tmt). Also, I managed to find a macro preprocessor that works with any language ([AnyMacro](https://github.com/xdevs23/anymacro)), so the port does use macros.
