### ISSUE TITLE
Terminal lose focus in scenes with other input nodes

### ISSUE THREAD

**Issue by ConteZero** [lihop/godot-xterm#51]
I'm using the Terminal node in a scene together with some LineEdit nodes.
When the focus is on the terminal, focus will switch to other LineEdit nodes after pressing some keys (KEY_UP, KEY_DOWN, KEY_TAB).

In `terminal.gd` I've changed:
```
func _gui_input(event):
	_native_terminal._gui_input(event)

	if event is InputEventKey and event.pressed:
		# Return to bottom of scrollback buffer if we scrolled up. Ignore modifier
		# keys pressed in isolation or if Ctrl+Shift modifier keys are pressed.
		if (
			not event.scancode in [KEY_ALT, KEY_SHIFT, KEY_CONTROL, KEY_META, KEY_MASK_CMD]
			and not (event.control and event.shift)
		):
			_native_terminal.sb_reset()

	_handle_mouse_wheel(event)
	_handle_selection(event)
```

with this:
```
func _input(event):
	if has_focus():
		_native_terminal._gui_input(event)

		if event is InputEventKey and event.pressed:
		# Return to bottom of scrollback buffer if we scrolled up. Ignore modifier
		# keys pressed in isolation or if Ctrl+Shift modifier keys are pressed.
			if (
				not event.scancode in [KEY_ALT, KEY_SHIFT, KEY_CONTROL, KEY_META, KEY_MASK_CMD]
				and not (event.control and event.shift)
			):
				_native_terminal.sb_reset()
			if event.scancode in [KEY_DOWN, KEY_UP, KEY_TAB]:
				get_tree().set_input_as_handled()

		_handle_mouse_wheel(event)
		_handle_selection(event)
```

This code solves the focus switch problem, but it is not the right fix because from my tests sometimes it causes some key press to be lost.

**Comment by lihop** [comment]
Hi @ConteZero, thanks for reporting this. I can reproduce the issue in [this scene](https://github.com/lihop/godot-xterm/pull/52/files#diff-7f50c05e7f713c9b51bb844277dc83329dcb39d5d971e5316d2908f54d1d36d0):

![issue](https://user-images.githubusercontent.com/3696783/182586795-4bea1286-5d65-47f0-a89f-a0027f82f23f.gif)

Can you try with this code instead and let me know if it fixes the problem:
```

func _gui_input(event):
	_native_terminal._gui_input(event)
	if event is InputEventKey and event.pressed:
		# Return to bottom of scrollback buffer if we scrolled up. Ignore modifier
		# keys pressed in isolation or if Ctrl+Shift modifier keys are pressed.
		if (
			not event.scancode in [KEY_ALT, KEY_SHIFT, KEY_CONTROL, KEY_META, KEY_MASK_CMD]
			and not (event.control and event.shift)
		):
			_native_terminal.sb_reset()

		if event.scancode in [KEY_LEFT, KEY_UP, KEY_RIGHT, KEY_DOWN, KEY_TAB]:
			accept_event()

	_handle_mouse_wheel(event)
	_handle_selection(event)
```

**Comment by ConteZero** [comment]
I can confirm that your code fixes the problem.
Thanks, your addon is really great!

**Comment by ConteZero** [comment]
I also encountered another problem, but I don't know if it can be related to this one.

With the same setup (scene with Terminal,Pty and other input nodes) if I execute a command with `sudo` the terminal screen do not show the command output, to force a refresh I need to press a key or click on other input field to switch focus.

The same command executed without `sudo` works as expected, the screen show the output.

`ping www.google.com` works
`sudo ping www.google.com` doesn't work
