### ISSUE TITLE
PTY output not shown without GUI activity

### ISSUE THREAD

**Issue by lihop** [lihop/godot-xterm#53]
I also encountered another problem, but I don't know if it can be related to this one.

With the same setup (scene with Terminal,Pty and other input nodes) if I execute a command with `sudo` the terminal screen do not show the command output, to force a refresh I need to press a key or click on other input field to switch focus.

The same command executed without `sudo` works as expected, the screen show the output.

`ping www.google.com` works
`sudo ping www.google.com` doesn't work

_Originally posted by @ConteZero in https://github.com/lihop/godot-xterm/issues/51#issuecomment-1203893058_

**Comment by lihop** [comment]
@ConteZero I am not able to reproduce this issue in the test scene:

![issue](https://user-images.githubusercontent.com/3696783/182972214-668cfb39-46f0-4ee1-a84c-fe39d237c221.gif)

However, I faced a similar issue when developing the integrated terminal EditorPlugin.

When making the integrated terminal for editor I noticed that the output would not update unless moving the cursor to focus on another panel or after some other type of gui activity (e.g. button click, scroll, cursor blink, etc.). The output from PTY is only updated by calling `poll()` in `_process()`:
https://github.com/lihop/godot-xterm/blob/2acb93f8ffee63ecbf8a46b38a864295566a06bf/addons/godot_xterm/nodes/pty/unix/pty_unix.gd#L129-L131

In editor, `_process()` is not continuously called unless the editor setting 'update continuously' is set to on:

![2022-08-05-113704_753x187_scrot](https://user-images.githubusercontent.com/3696783/182972764-46fafe03-8de3-4d81-aaad-ded2c0dc6729.png)

However, this issue affected all command output regardless of whether it had `sudo` or not:

![issue2](https://user-images.githubusercontent.com/3696783/182974393-165a12f3-43c4-4912-aa96-ef969d7bb46c.gif)

My workaround was to add a timer to regularly call `poll()` on the underlying pipe:
https://github.com/lihop/godot-xterm/blob/3b7bdfc5ca6e44323e7c0a94832222d32b2bea8e/addons/godot_xterm/editor_plugins/terminal/editor_terminal.gd#L54-L66

I now notice that `_physics_process()` *is* called continuously in editor, so I will consider moving the poll from `_process()` to `_physics_process()` or adding a `process_mode` property (like Timer has) to choose between the two.

Could you try changing `func _process(_delta)` in `addons/godot_xterm/nodes/pty/unix/pty_unix.gd` to `func _physics_process(_delta)`, or force a regular update by calling `pty.get_master().poll()` with a timer?

<img align="right" src="https://user-images.githubusercontent.com/3696783/182994190-dd4b4eda-bba6-4c3a-b5a8-2a95381343ff.png">

Also, on the off chance that the issue isn't related to the PTY node, but rather the update functions of the Terminal node, you could try setting the `update_mode` property of Terminal to `All` (although this will have a slight performance penalty).

If none of these suggestions fix the problem, then I would be interested in more details about your scene setup and operating system version/environment to try and reproduce the issue and figure out why `sudo` commands might affect the output differently.

**Comment by ConteZero** [comment]
After doing same code changes to my project now I have the same update problem with and without `sudo` (`update_mode` is set to `All`), probably the differences between the two modes were caused by something wrong with my code.

Luckily your suggestion solves the problem, I've added to my `terminal.gd`:
```
func _on_PTY_data_received(data):
#	parsing 'data' code
	_poll()


func _poll():
	if visible and pty and pty.has_method("get_master"): 
		pty.get_master().poll() 
		update()
```
Thanks for your help.

**Comment by lihop** [comment]
After digging a bit deeper, I have found that simply adding `update()` at the end of terminal's write function fixes the issue I outlined above, and removes the need for a timer with the editor plugin.

@ConteZero Would you be able to undo the changes you made above and, in `terminal.gd`, change this code:
```
func write(data) -> void:
	assert(data is String or data is PoolByteArray)

	# Will be cleared when _flush() is called after VisualServer emits the "frame_pre_draw" signal.
	_buffer.push_back(data)
```
to this:
```
func write(data) -> void:
	assert(data is String or data is PoolByteArray)

	# Will be cleared when _flush() is called after VisualServer emits the "frame_pre_draw" signal.
	_buffer.push_back(data)
	update()
```
and let me know if that also fixes the problem?

**Comment by ConteZero** [comment]
I did various tests using `_poll()`, initially seemed to have solved the problem, instead I found that sometimes some data was not written on the terminal screen.

For now your last solution seems to work well, the only drawback is that it slowdown the execution when the terminal is not visible.
I've changed it to:
```
func write(data) -> void:
	assert(data is String or data is PoolByteArray)

	# Will be cleared when _flush() is called after VisualServer emits the "frame_pre_draw" signal.
	_buffer.push_back(data)
	if visible:
		update()
```
This change avoid the slowdown but I don't know if it's right and if it can have unwanted side effects.

**Comment by lihop** [comment]
> For now your last solution seems to work well, the only drawback is that it slowdown the execution when the terminal is not visible.

@ConteZero Could you try the last solution but with the terminal's `update_mode` set to the default of `Auto` rather than `All`? I'm curious to know if it will still slowdown execution.

Otherwise, I can't think of any unwanted side effect that calling `update()` only if visible would have.

**Comment by ConteZero** [comment]
There are no speed differences between  `update_mode` `Auto` and `All`.
